#
# Copyright 2021 The Kubernetes Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelapp
  labels:
    app: travelapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelapp
  template:
    metadata:
      labels:
        app: travelapp
    spec:
      containers:
      - name: travelapp-container
        command: ["echo", "Deserunt elit nostrud elit magna culpa ea irure deserunt do excepteur aliqua dolor. Proident voluptate fugiat eiusmod pariatur mollit pariatur. Id magna tempor est anim ipsum est.
    Nulla officia magna exercitation elit laborum veniam exercitation reprehenderit incididunt deserunt. Laboris tempor id nulla id commodo reprehenderit ipsum ullamco cupidatat et anim anim. Minim labore cillum qui eu nostrud consectetur amet ipsum deserunt eiusmod eiusmod consectetur. In mollit officia id labore commodo adipisicing aliqua elit dolore tempor nostrud magna. Exercitation ut laboris culpa dolore sit esse commodo eu exercitation commodo qui.
    Amet nisi pariatur exercitation eiusmod ad esse aliquip nulla deserunt voluptate ea. Dolor elit Lorem qui minim ex non magna esse id. Adipisicing laboris eiusmod voluptate qui consectetur nisi velit adipisicing adipisicing voluptate reprehenderit non. Commodo ad voluptate minim ea ea veniam deserunt enim laboris. Aute sint duis in esse qui consequat mollit id cillum cillum. Eiusmod ex Lorem duis dolore sit in ad ad ex eu consectetur consectetur.
    Laboris Lorem deserunt tempor cupidatat elit sit duis nostrud eu nisi qui enim laboris. Laboris commodo nulla reprehenderit incididunt proident veniam do. Sint cupidatat esse elit ut officia qui commodo consectetur enim non dolor eu.
    Excepteur sunt dolor sit enim duis sit aute. Veniam magna dolor ipsum dolor ea incididunt labore tempor velit enim tempor quis pariatur. Laboris commodo enim Lorem exercitation ut laborum duis ea qui. Quis sint aliquip incididunt nisi non sit. Amet elit ex pariatur et excepteur enim occaecat duis est laborum nostrud magna eu quis. Exercitation laboris qui nisi et deserunt occaecat dolore nisi fugiat. Ad laborum fugiat sunt tempor quis duis eiusmod proident.
    Ipsum excepteur non duis in laboris duis anim velit. Sit proident adipisicing do et ipsum. Cupidatat laborum labore ut et dolore incididunt ullamco minim. Sunt commodo esse est excepteur eiusmod dolore.
    Deserunt nisi cillum consequat reprehenderit exercitation est reprehenderit in do labore. Consectetur officia ipsum sint culpa tempor consectetur ad. Dolor id commodo velit nisi anim nostrud id ipsum consectetur pariatur. Incididunt laborum aliqua veniam laborum culpa et pariatur consectetur. Ad anim magna magna incididunt irure enim laboris laboris adipisicing cillum voluptate.
    Officia elit laboris non quis tempor est. Tempor incididunt sint mollit mollit consequat eu ex fugiat cupidatat. Culpa magna commodo veniam laboris tempor labore amet cillum magna eiusmod aliqua.
    Velit ipsum enim amet sit. Lorem adipisicing amet incididunt consectetur ullamco nulla enim non id. Irure elit culpa tempor adipisicing exercitation non sunt aliqua do est.", "\nThe magic key is 6120758", 
    "\nOccaecat aliqua cillum elit adipisicing aliqua pariatur eu officia labore cillum voluptate Lorem ipsum. Voluptate ut exercitation sit voluptate tempor officia id cupidatat dolor sit dolor consectetur incididunt sint. Esse deserunt veniam deserunt incididunt ullamco et incididunt sint.
    Et quis consequat cillum aute eu nostrud. Laborum nostrud reprehenderit fugiat aute deserunt nostrud in. Magna duis dolore minim ipsum mollit sint eiusmod nulla consequat enim aute sint laborum irure. Irure excepteur culpa occaecat enim do est duis velit incididunt cupidatat consectetur dolore.
    Laboris voluptate pariatur laboris voluptate qui incididunt adipisicing commodo nostrud ea. Eiusmod est aliqua elit tempor consectetur. Cupidatat consectetur exercitation veniam excepteur fugiat nisi aliqua magna id minim excepteur sit. Exercitation esse ullamco officia laborum. Quis nostrud in aliqua non dolore eu dolor commodo veniam dolor deserunt enim sunt. Cillum excepteur duis sunt amet. Ipsum enim quis pariatur aute amet ipsum fugiat.
    Nisi adipisicing occaecat sit nostrud ea sit proident voluptate est cupidatat deserunt. Magna pariatur excepteur quis sint irure. Aute dolor laborum consectetur sint est culpa minim. Sit deserunt cillum quis cupidatat nisi labore mollit. Magna minim esse magna irure sint et id esse mollit ut excepteur. Amet veniam qui voluptate eu culpa labore id commodo in nostrud aute esse tempor.
    Aliquip nostrud magna dolore amet pariatur eiusmod est. Labore fugiat pariatur sint ut anim enim amet nostrud reprehenderit consectetur. Duis tempor consequat occaecat voluptate anim duis laborum magna do mollit laborum fugiat aliquip. Nisi magna enim voluptate sit sunt minim consectetur culpa consequat amet pariatur qui incididunt ad. Ut nisi quis pariatur aliqua irure sit. Ipsum non excepteur esse enim culpa esse officia labore sit.
    Non ipsum sint excepteur nostrud eu est laborum aute dolore sint deserunt laborum sint. Velit commodo non quis cupidatat ad proident. Qui id reprehenderit adipisicing veniam occaecat anim mollit commodo aliquip id velit.
    Laborum exercitation mollit consectetur sint eiusmod laborum amet. Nostrud ea in consequat anim officia dolore velit cupidatat nulla velit ullamco. Consectetur labore tempor minim enim exercitation consequat. Non et eu est anim est magna. Esse adipisicing non ut est fugiat consectetur nisi quis cupidatat do esse nisi. Id commodo pariatur ad excepteur voluptate tempor duis nostrud aliquip adipisicing commodo nostrud.
    Qui commodo mollit reprehenderit enim ipsum. Et laboris Lorem amet sunt eu. Ullamco aute non nisi nulla velit dolor eu ad. Non ad in mollit id cupidatat. Magna cillum eu exercitation non aliquip magna excepteur in quis excepteur. Fugiat sint est in ex sunt qui dolor non voluptate officia ea pariatur consectetur officia. Qui consequat nisi fugiat pariatur ea.
    Mollit eiusmod magna cillum voluptate. Quis labore consectetur proident Lorem occaecat adipisicing do aute reprehenderit minim esse. Tempor ullamco est id dolor laboris in consectetur exercitation aliqua magna. Cillum laboris non dolore nostrud sit.
    Aute velit voluptate consectetur fugiat laborum nulla exercitation nisi velit eu ex exercitation. Ut velit exercitation proident exercitation aute anim culpa irure proident id anim amet quis. Culpa amet incididunt irure ex quis proident est elit proident. Enim magna fugiat consectetur eiusmod eiusmod ipsum minim qui deserunt anim ad aliquip velit sunt. Aliqua incididunt aute Lorem est ipsum adipisicing irure sit. Duis ex et cupidatat excepteur labore amet nisi fugiat laborum irure deserunt do culpa cupidatat. Sunt do aliqua pariatur exercitation minim amet commodo esse est et do occaecat sunt fugiat.
    Qui esse dolor ad nostrud veniam aliquip. Veniam sit non pariatur irure ut in veniam aliquip velit dolor sit. Voluptate minim aliquip officia voluptate laborum dolore commodo nostrud labore."]
        image: quay.io/bitnami/nginx:latest
        ports:
        - containerPort: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: travelapp-hpa
  labels:
    app: travelapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: travelapp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
